link-shortener:
  short-link-length: 8

logging:
  log-execution-time: true
  web-logging: true
  log-request-body: true

spring:
  main:
    banner-mode: off

scheduling:
  cron:
    delete-link-infos: '0 0 23 * * *'
#    delete-link-infos: '* * * * * *'